# Generated by Django 4.2.2 on 2023-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_created_at_candidate_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
