# Generated by Django 4.2.2 on 2023-06-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='candidate_images'),
        ),
    ]
